///////////////////////////////////////////////////////////
//  PushDataService.cs
//  Implementation of the Class PushDataService
//  Generated by Enterprise Architect
//  Created on:      16-七月-2012 11:18:14
//  Original author: wayne
///////////////////////////////////////////////////////////




namespace Frameworks.DataTransfer {
	/// <summary>
	/// 推送数据到服务器端
	/// </summary>
	public class PushDataService {

		public PushDataService(){

		}

		~PushDataService(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="info"></param>
		public void Begin(DataInfo info){

		}

		/// 
		/// <param name="dataid"></param>
		/// <param name="abandon"></param>
		public void End(String dataid, bool abandon){

		}

		/// 
		/// <param name="segment"></param>
		public void Push(DataSegment segment){

		}

	}//end PushDataService

}//end namespace DataTransfer