/*
insert license info here
*/
using System;

namespace Daan.DataTransfer.Test.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Dicttableversion : DomainBase
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private float _dicttableversionid; 
		private string _tablename; 
		private float _versioncount; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Dicttableversion()
		{
			_dicttableversionid = 0; 
			_tablename = null; 
			_versioncount = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键，自动ID
		/// </summary>		
		public float Dicttableversionid
		{
			get { return _dicttableversionid; }
			set { _isChanged |= (_dicttableversionid != value); _dicttableversionid = value; }
		}
			
		/// <summary>
		/// 表名
		/// </summary>		
		public string Tablename
		{
			get { return _tablename; }
			set	
			{
				if( value!= null && value.Length > 40)
					throw new ArgumentOutOfRangeException("Invalid value for Tablename", value, value.ToString());
				
				_isChanged |= (_tablename != value); _tablename = value;
			}
		}
			
		/// <summary>
		/// 版本号
		/// </summary>		
		public float Versioncount
		{
			get { return _versioncount; }
			set { _isChanged |= (_versioncount != value); _versioncount = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
