/*
insert license info here
*/
using System;

namespace Daan.DataTransfer.Test.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Dictcustomerdiscount : DomainBase
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private float _dictcustomerdiscountid; 
		private float _dictcustomerid; 
		private float _discount; 
		private DateTime _begindate; 
		private DateTime _enddate; 
		private float _updateby; 
		private DateTime _updatedate; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Dictcustomerdiscount()
		{
			_dictcustomerdiscountid = 0; 
			_dictcustomerid = 0; 
			_discount = 0; 
			_begindate = new DateTime(); 
			_enddate = new DateTime(); 
			_updateby = 0; 
			_updatedate = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键，自动ID
		/// </summary>		
		public float Dictcustomerdiscountid
		{
			get { return _dictcustomerdiscountid; }
			set { _isChanged |= (_dictcustomerdiscountid != value); _dictcustomerdiscountid = value; }
		}
			
		/// <summary>
		/// 顾客ID
		/// </summary>		
		public float Dictcustomerid
		{
			get { return _dictcustomerid; }
			set { _isChanged |= (_dictcustomerid != value); _dictcustomerid = value; }
		}
			
		/// <summary>
		/// 折扣
		/// </summary>		
		public float Discount
		{
			get { return _discount; }
			set { _isChanged |= (_discount != value); _discount = value; }
		}
			
		/// <summary>
		/// 此折扣开始时间
		/// </summary>		
		public DateTime Begindate
		{
			get { return _begindate; }
			set { _isChanged |= (_begindate != value); _begindate = value; }
		}
			
		/// <summary>
		/// 此折扣结束时间
		/// </summary>		
		public DateTime Enddate
		{
			get { return _enddate; }
			set { _isChanged |= (_enddate != value); _enddate = value; }
		}
			
		/// <summary>
		/// 维护人
		/// </summary>		
		public float Updateby
		{
			get { return _updateby; }
			set { _isChanged |= (_updateby != value); _updateby = value; }
		}
			
		/// <summary>
		/// 维护日期
		/// </summary>		
		public DateTime Updatedate
		{
			get { return _updatedate; }
			set { _isChanged |= (_updatedate != value); _updatedate = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
