/*
insert license info here
*/
using System;

namespace Daan.DataTransfer.Test.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Dictusergroup : DomainBase
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private float _dictusergroupid; 
		private string _groupcode; 
		private string _groupname; 
		private string _groupnote; 
		private string _active; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Dictusergroup()
		{
			_dictusergroupid = 0; 
			_groupcode = null; 
			_groupname = null; 
			_groupnote = null; 
			_active = null; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 自动编码
		/// </summary>		
		public float Dictusergroupid
		{
			get { return _dictusergroupid; }
			set { _isChanged |= (_dictusergroupid != value); _dictusergroupid = value; }
		}
			
		/// <summary>
		/// 权限组编码
		/// </summary>		
		public string Groupcode
		{
			get { return _groupcode; }
			set	
			{
				if( value!= null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for Groupcode", value, value.ToString());
				
				_isChanged |= (_groupcode != value); _groupcode = value;
			}
		}
			
		/// <summary>
		/// 权限组名称
		/// </summary>		
		public string Groupname
		{
			get { return _groupname; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Groupname", value, value.ToString());
				
				_isChanged |= (_groupname != value); _groupname = value;
			}
		}
			
		/// <summary>
		/// 描述
		/// </summary>		
		public string Groupnote
		{
			get { return _groupnote; }
			set	
			{
				if( value!= null && value.Length > 300)
					throw new ArgumentOutOfRangeException("Invalid value for Groupnote", value, value.ToString());
				
				_isChanged |= (_groupnote != value); _groupnote = value;
			}
		}
			
		/// <summary>
		/// 是否可用
		/// </summary>		
		public string Active
		{
			get { return _active; }
			set	
			{
				if( value!= null && value.Length > 1)
					throw new ArgumentOutOfRangeException("Invalid value for Active", value, value.ToString());
				
				_isChanged |= (_active != value); _active = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
