/*
insert license info here
*/
using System;

namespace Daan.DataTransfer.Test.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Dicttestitemmodel : DomainBase
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private float _dicttestitemmodelid; 
		private string _modeltitle; 
		private DateTime _createdate; 
		private float _orderby; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Dicttestitemmodel()
		{
			_dicttestitemmodelid = 0; 
			_modeltitle = null; 
			_createdate = new DateTime(); 
			_orderby = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键，自增长
		/// </summary>		
		public float Dicttestitemmodelid
		{
			get { return _dicttestitemmodelid; }
			set { _isChanged |= (_dicttestitemmodelid != value); _dicttestitemmodelid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Modeltitle
		{
			get { return _modeltitle; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Modeltitle", value, value.ToString());
				
				_isChanged |= (_modeltitle != value); _modeltitle = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime Createdate
		{
			get { return _createdate; }
			set { _isChanged |= (_createdate != value); _createdate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public float Orderby
		{
			get { return _orderby; }
			set { _isChanged |= (_orderby != value); _orderby = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
