/*
insert license info here
*/
using System;

namespace Daan.DataTransfer.Test.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Dictantibioticrefrange : DomainBase
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private float _dictantibioticrefrangeid; 
		private float _dicttantibioticgroupid; 
		private float _dictantibioticid; 
		private float _kbrbegin; 
		private float _kbsbegin; 
		private float _micrbegin; 
		private float _micsbegin; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Dictantibioticrefrange()
		{
			_dictantibioticrefrangeid = 0; 
			_dicttantibioticgroupid = 0; 
			_dictantibioticid = 0; 
			_kbrbegin = 0; 
			_kbsbegin = 0; 
			_micrbegin = 0; 
			_micsbegin = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键，自动ID
		/// </summary>		
		public float Dictantibioticrefrangeid
		{
			get { return _dictantibioticrefrangeid; }
			set { _isChanged |= (_dictantibioticrefrangeid != value); _dictantibioticrefrangeid = value; }
		}
			
		/// <summary>
		/// 抗生素标准分组ID
		/// </summary>		
		public float Dicttantibioticgroupid
		{
			get { return _dicttantibioticgroupid; }
			set { _isChanged |= (_dicttantibioticgroupid != value); _dicttantibioticgroupid = value; }
		}
			
		/// <summary>
		/// 抗生素ID
		/// </summary>		
		public float Dictantibioticid
		{
			get { return _dictantibioticid; }
			set { _isChanged |= (_dictantibioticid != value); _dictantibioticid = value; }
		}
			
		/// <summary>
		/// KB法抗生素耐药起始值，一般显示为<=XX
		/// </summary>		
		public float Kbrbegin
		{
			get { return _kbrbegin; }
			set { _isChanged |= (_kbrbegin != value); _kbrbegin = value; }
		}
			
		/// <summary>
		/// KB法抗生素敏感起始值，一般显示为>=XX
		/// </summary>		
		public float Kbsbegin
		{
			get { return _kbsbegin; }
			set { _isChanged |= (_kbsbegin != value); _kbsbegin = value; }
		}
			
		/// <summary>
		/// KB法抗生素耐药起始值，一般显示为<=XX
		/// </summary>		
		public float Micrbegin
		{
			get { return _micrbegin; }
			set { _isChanged |= (_micrbegin != value); _micrbegin = value; }
		}
			
		/// <summary>
		/// KB法抗生素敏感起始值，一般显示为>=XX
		/// </summary>		
		public float Micsbegin
		{
			get { return _micsbegin; }
			set { _isChanged |= (_micsbegin != value); _micsbegin = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
