/*
insert license info here
*/
using System;

namespace Daan.DataTransfer.Test.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Dictrouteassign : DomainBase
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private float _dictrouteassignid; 
		private float _dictuserid; 
		private float _dictrouteid; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Dictrouteassign()
		{
			_dictrouteassignid = 0; 
			_dictuserid = 0; 
			_dictrouteid = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键，自动ID
		/// </summary>		
		public float Dictrouteassignid
		{
			get { return _dictrouteassignid; }
			set { _isChanged |= (_dictrouteassignid != value); _dictrouteassignid = value; }
		}
			
		/// <summary>
		/// 用户ID
		/// </summary>		
		public float Dictuserid
		{
			get { return _dictuserid; }
			set { _isChanged |= (_dictuserid != value); _dictuserid = value; }
		}
			
		/// <summary>
		/// 线路ID
		/// </summary>		
		public float Dictrouteid
		{
			get { return _dictrouteid; }
			set { _isChanged |= (_dictrouteid != value); _dictrouteid = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
