/*
insert license info here
*/
using System;

namespace Daan.DataTransfer.Test.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Dictcontroltestrule : DomainBase
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private float _dictcontroltestruleid; 
		private float _dictcontrolid; 
		private float _dicttestitemid; 
		private float _qcruleid; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Dictcontroltestrule()
		{
			_dictcontroltestruleid = 0; 
			_dictcontrolid = 0; 
			_dicttestitemid = 0; 
			_qcruleid = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键，自动ID
		/// </summary>		
		public float Dictcontroltestruleid
		{
			get { return _dictcontroltestruleid; }
			set { _isChanged |= (_dictcontroltestruleid != value); _dictcontroltestruleid = value; }
		}
			
		/// <summary>
		/// 质控水平ID，对应表DICTQCCONTROL
		/// </summary>		
		public float Dictcontrolid
		{
			get { return _dictcontrolid; }
			set { _isChanged |= (_dictcontrolid != value); _dictcontrolid = value; }
		}
			
		/// <summary>
		/// 测试项ID，对应表TESTITEM
		/// </summary>		
		public float Dicttestitemid
		{
			get { return _dicttestitemid; }
			set { _isChanged |= (_dicttestitemid != value); _dicttestitemid = value; }
		}
			
		/// <summary>
		/// 规则ID，对应表DICTLIABRARY
		/// </summary>		
		public float Qcruleid
		{
			get { return _qcruleid; }
			set { _isChanged |= (_qcruleid != value); _qcruleid = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
