/*
insert license info here
*/
using System;

namespace Daan.DataTransfer.Test.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Dictcustomertestdiscount : DomainBase
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private float _dictcustomerdiscountid; 
		private float _dictcustomerid; 
		private float _dicttestitemid; 
		private float _standardprice; 
		private float _customerprice; 
		private float _finalprice; 
		private float _discount; 
		private DateTime _begindate; 
		private DateTime _enddate; 
		private float _updateby; 
		private DateTime _updatedate; 
		private float _sendoutprice; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Dictcustomertestdiscount()
		{
			_dictcustomerdiscountid = 0; 
			_dictcustomerid = 0; 
			_dicttestitemid = 0; 
			_standardprice = 0; 
			_customerprice = 0; 
			_finalprice = 0; 
			_discount = 0; 
			_begindate = new DateTime(); 
			_enddate = new DateTime(); 
			_updateby = 0; 
			_updatedate = new DateTime(); 
			_sendoutprice = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 主键，自动ID
		/// </summary>		
		public float Dictcustomerdiscountid
		{
			get { return _dictcustomerdiscountid; }
			set { _isChanged |= (_dictcustomerdiscountid != value); _dictcustomerdiscountid = value; }
		}
			
		/// <summary>
		/// 客户ID
		/// </summary>		
		public float Dictcustomerid
		{
			get { return _dictcustomerid; }
			set { _isChanged |= (_dictcustomerid != value); _dictcustomerid = value; }
		}
			
		/// <summary>
		/// 测试项ID
		/// </summary>		
		public float Dicttestitemid
		{
			get { return _dicttestitemid; }
			set { _isChanged |= (_dicttestitemid != value); _dicttestitemid = value; }
		}
			
		/// <summary>
		/// 标准价钱
		/// </summary>		
		public float Standardprice
		{
			get { return _standardprice; }
			set { _isChanged |= (_standardprice != value); _standardprice = value; }
		}
			
		/// <summary>
		/// 客户定价
		/// </summary>		
		public float Customerprice
		{
			get { return _customerprice; }
			set { _isChanged |= (_customerprice != value); _customerprice = value; }
		}
			
		/// <summary>
		/// 最终价钱
		/// </summary>		
		public float Finalprice
		{
			get { return _finalprice; }
			set { _isChanged |= (_finalprice != value); _finalprice = value; }
		}
			
		/// <summary>
		/// 折扣
		/// </summary>		
		public float Discount
		{
			get { return _discount; }
			set { _isChanged |= (_discount != value); _discount = value; }
		}
			
		/// <summary>
		/// 开始日期
		/// </summary>		
		public DateTime Begindate
		{
			get { return _begindate; }
			set { _isChanged |= (_begindate != value); _begindate = value; }
		}
			
		/// <summary>
		/// 结束日期
		/// </summary>		
		public DateTime Enddate
		{
			get { return _enddate; }
			set { _isChanged |= (_enddate != value); _enddate = value; }
		}
			
		/// <summary>
		/// 维护人
		/// </summary>		
		public float Updateby
		{
			get { return _updateby; }
			set { _isChanged |= (_updateby != value); _updateby = value; }
		}
			
		/// <summary>
		/// 维护日期
		/// </summary>		
		public DateTime Updatedate
		{
			get { return _updatedate; }
			set { _isChanged |= (_updatedate != value); _updatedate = value; }
		}
			
		/// <summary>
		/// --
		/// </summary>		
		public float Sendoutprice
		{
			get { return _sendoutprice; }
			set { _isChanged |= (_sendoutprice != value); _sendoutprice = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
