/*
insert license info here
*/
using System;

namespace Daan.DataTransfer.Test.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class Distributedetail : DomainBase
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private string _rackbarcode; 
		private string _subbarcode; 
		private float _xpos; 
		private float _ypos; 
		private DateTime _createdate; 
		private float _distributeby; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Distributedetail()
		{
			_rackbarcode = null; 
			_subbarcode = null; 
			_xpos = 0; 
			_ypos = 0; 
			_createdate = new DateTime(); 
			_distributeby = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 架子条码号
		/// </summary>		
		public string Rackbarcode
		{
			get { return _rackbarcode; }
			set	
			{
				if( value!= null && value.Length > 40)
					throw new ArgumentOutOfRangeException("Invalid value for Rackbarcode", value, value.ToString());
				
				_isChanged |= (_rackbarcode != value); _rackbarcode = value;
			}
		}
			
		/// <summary>
		/// 条码号
		/// </summary>		
		public string Subbarcode
		{
			get { return _subbarcode; }
			set	
			{
				if( value!= null && value.Length > 40)
					throw new ArgumentOutOfRangeException("Invalid value for Subbarcode", value, value.ToString());
				
				_isChanged |= (_subbarcode != value); _subbarcode = value;
			}
		}
			
		/// <summary>
		/// 架子X坐标
		/// </summary>		
		public float Xpos
		{
			get { return _xpos; }
			set { _isChanged |= (_xpos != value); _xpos = value; }
		}
			
		/// <summary>
		/// 架子Y坐标
		/// </summary>		
		public float Ypos
		{
			get { return _ypos; }
			set { _isChanged |= (_ypos != value); _ypos = value; }
		}
			
		/// <summary>
		/// 记录生成日期
		/// </summary>		
		public DateTime Createdate
		{
			get { return _createdate; }
			set { _isChanged |= (_createdate != value); _createdate = value; }
		}
			
		/// <summary>
		/// 分发人
		/// </summary>		
		public float Distributeby
		{
			get { return _distributeby; }
			set { _isChanged |= (_distributeby != value); _distributeby = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
