///////////////////////////////////////////////////////////
//  DataParameter.cs
//  Implementation of the Class DataParameter
//  Generated by Enterprise Architect
//  Created on:      12-七月-2012 11:11:49
//  Original author: wayne
///////////////////////////////////////////////////////////


using System;

namespace Daan.DataTransfer.DataCommon
{
    [Serializable]
    public class DataParameter
    {
        /// <summary>
        /// 操作描述
        /// </summary>
        public int Action { get; set; }
        public string CrcCode { get; set; }
        /// <summary>
        /// 数据内容
        /// </summary>
        public string DataString { get; set; }
    }
}