///////////////////////////////////////////////////////////
//  DataResult.cs
//  Implementation of the Class DataResult
//  Generated by Enterprise Architect
//  Created on:      12-七月-2012 11:12:01
//  Original author: wayne
///////////////////////////////////////////////////////////


using System;
using Daan.DataTransfer.DataCommon;
namespace Daan.DataTransfer.DataCommon
{
    [Serializable]
	public class DataResult : DataParameter {

        public string DataId { get; set; }
		/// <summary>
		/// 自定义错误id
		/// </summary>
        public int ErrorId
        {
            get;
            set;
		}
		/// <summary>
		/// 错误密码
		/// </summary>
        public string ErrorMessage
        {
            get;
            set;
		}
		/// <summary>
		/// 拆分后总数
		/// </summary>
        public int SplitCount
        {
            get;
            set;
		}

		

		

	}//end DataResult

}//end namespace DataTransfer