///////////////////////////////////////////////////////////
//  DataObjectConvert.cs
//  Implementation of the Interface DataObjectConvert
//  Generated by Enterprise Architect
//  Created on:      12-七月-2012 11:11:35
//  Original author: wayne
///////////////////////////////////////////////////////////




using Daan.DataTransfer.DataCommon;
namespace Daan.DataTransfer.DataCommon {
	public interface IDataObjectConvert {

		/// <summary>
		/// 将结果转成DataResult对象
		/// </summary>
		/// <param name="objects"></param>
		DataResult ObjectToResult<T>(T objects);

		/// <summary>
		/// 可以使用模板方法实现
		/// </summary>
		/// <param name="parameter"></param>
		T ParameterToObject<T>(DataParameter parameter);
	}//end DataObjectConvert

}//end namespace DataTransfer